// Rebuild the offline app resource from the same accepted rig and motion modules.
// Data-URL import maps preserve real ES module scopes without a second bundler.
import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {root,toolRoot,previewRoot} from './paths.mjs';
export async function nativeHTML(){
 const names=['elastic-body.mjs','wave-contact.mjs','voice-scene.mjs','mesh-renderer.mjs','return-state.mjs'],imports={};
 for(const name of names){let source=await readFile(resolve(previewRoot,name),'utf8');source=source.replace(/(['"])\.\/([\w-]+\.mjs)\1/g,(_,quote,file)=>`${quote}@review-motion/${file}${quote}`);imports['@review-motion/'+name]='data:text/javascript;base64,'+Buffer.from(source).toString('base64');}
 const json=JSON.parse(await readFile(resolve(previewRoot,'data/mascot.json'),'utf8'));
 json.animations={recall:json.animations.recall,rest:json.animations.rest};
 const atlas=await readFile(resolve(previewRoot,'data/images/mascot.atlas'),'utf8'),images={};
 for(const name of ['body.png','eye.png','pupil.png','fragment.png','shadow.png'])images[name]='data:image/png;base64,'+(await readFile(resolve(previewRoot,'data/images',name))).toString('base64');
 const runtime=await readFile(resolve(toolRoot,'node_modules/@esotericsoftware/spine-canvas/dist/iife/spine-canvas.min.js'),'utf8');
 const entry=await readFile(resolve(toolRoot,'src/native-player.mjs'),'utf8');
 const safe=text=>text.replace(/<\/script/gi,'<\\/script');
 return `<!doctype html><!-- Generated by tools/mascot-motion/src/build-native.mjs; do not edit. -->
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' data:; img-src data:; style-src 'unsafe-inline'; connect-src 'none'">
<style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent}canvas{display:block;width:100%;height:100%;pointer-events:none}</style>
<canvas aria-hidden="true"></canvas>
<script type="importmap">${JSON.stringify({imports})}</script>
<script type="application/json" id="rig-data">${safe(JSON.stringify({json,atlas,images}))}</script>
<script>${safe(runtime)}</script><script type="module">${safe(entry)}</script>`;
}
const html=await nativeHTML(),destination=resolve(root,'Review_Today/MascotMotion.html');
if(process.argv.includes('--check')){if(await readFile(destination,'utf8')!==html)throw Error('Native mascot resource is stale; run build-native.mjs');console.log('Native animation resource matches its source.');}
else {await writeFile(destination,html);console.log(destination,Buffer.byteLength(html),'bytes');}
